/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import aplicacao.Mensagem;
import aplicacao.Pacote;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.net.InetAddress;
import java.net.Socket;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import service.ClienteService;

/**
 *
 * @author LORD
 */
public class EnvioDeMensagens extends javax.swing.JFrame {

    private Socket socket;
    private Mensagem mensagem;
    private ClienteService service;
    private Pacote pacote;
    private String IpOrigem;
    private String IpDestino;

    public EnvioDeMensagens() {
        initComponents();

        pnlPacoteEnvio.setVisible(false);
        pnlPacoteRecebe.setVisible(false);
        jList1.setVisible(false);
        jInternalFrameMensagem.setVisible(true);

    }

    private class ListenerSocket implements Runnable {

        private ObjectInputStream input;

        public ListenerSocket(Socket socket) {

            try {

                this.input = new ObjectInputStream(socket.getInputStream());

            } catch (IOException ex) {
                Logger.getLogger(TelaParametros.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        @Override
        public void run() {
            Mensagem mensagem = null;

            try {
                while ((mensagem = (Mensagem) input.readObject()) != null) {

                    Mensagem.Action action = mensagem.getAction();

                    if (action.equals(Mensagem.Action.DISCONECTAR)) {
                        disconectar();
                        socket.close();

                    } else if (action.equals(Mensagem.Action.ENVIAR)) {
                        receber(mensagem);
                        System.out.println(mensagem.getPacotes().size());
                    }
                }
            } catch (IOException ex) {
                disconectar();
                Logger.getLogger(TelaParametros.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(TelaParametros.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }

    private void disconectar() {

        JOptionPane.showMessageDialog(this, "Obrigado por utilizar");
    }

    private void receber(Mensagem mensagem) {

        if (mensagem.getPacotes().get(retornaUltimoPacote(mensagem)).isAceito()) {
            preencherCampos(mensagem);
            pnlPacoteEnvio.setVisible(true);
        } else {
            pnlPacoteRecebe.setVisible(true);
            btnAceitar.setVisible(true);
            btnRecusar.setVisible(false);
            btnConfirmaEnvio.setVisible(true);
            btnConfirmaEnvio.setEnabled(false);
        }
        //verificarConteudo(mensagem);
        this.mensagem = mensagem;

        preencherCampos(mensagem);
        System.out.println("Pacotes ao receber: " + mensagem.getPacotes().size());
    }

    private void preencherCampos(Mensagem mensagem) {

        if (mensagem.getPacotes().get(retornaUltimoPacote(mensagem)).isAceito()) {
            pnlPacoteEnvio.setVisible(true);
            btnConfirmaEnvio.setVisible(true);
            jProgressBarEnvio.setVisible(false);
        } //if(mensagem.getIpOrigem() == máquina local )
        else {
            pnlPacoteEnvio.setVisible(true);
            btnConfirmaEnvio.setVisible(false);
            jProgressBarEnvio.setVisible(true);

        }
    }

    private int retornaUltimoPacote(Mensagem mensagem) {

        return (mensagem.getPacotes().size() - 1);

    }

    protected void camposAtivosInicio(){
        
        try {
            if (IpOrigem == InetAddress.getLocalHost().getHostAddress()) {

                jInternalFrameMensagem.setVisible(false);
                
            }
        } catch (UnknownHostException ex) {
            Logger.getLogger(EnvioDeMensagens.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        pnlPrincipal = new javax.swing.JPanel();
        pnlPacoteRecebe = new javax.swing.JPanel();
        pnlDadosPacoteRecebe = new javax.swing.JPanel();
        txtIpDestino2 = new javax.swing.JFormattedTextField();
        lblIpDestino2 = new javax.swing.JLabel();
        lblPortaDestino2 = new javax.swing.JLabel();
        txtTamanhoDadosPacote2 = new javax.swing.JTextField();
        txtJanelaRecepcao2 = new javax.swing.JFormattedTextField();
        lblTamanhoDadosPacote2 = new javax.swing.JLabel();
        txtPortaDestino2 = new javax.swing.JFormattedTextField();
        lblJanelaRecepcao2 = new javax.swing.JLabel();
        lblTamanhoCabecalho2 = new javax.swing.JLabel();
        chkSYN2 = new javax.swing.JCheckBox();
        txtNumeroSequencia2 = new javax.swing.JFormattedTextField();
        chkACK2 = new javax.swing.JCheckBox();
        txtNumeroRecepcao2 = new javax.swing.JFormattedTextField();
        chkRST2 = new javax.swing.JCheckBox();
        chkFIN2 = new javax.swing.JCheckBox();
        lblChecksum2 = new javax.swing.JLabel();
        lblNumeroSequencia2 = new javax.swing.JLabel();
        lblUrgentPointer2 = new javax.swing.JLabel();
        chkURG2 = new javax.swing.JCheckBox();
        lblOptions2 = new javax.swing.JLabel();
        txtTamanhoCabecalho2 = new javax.swing.JTextField();
        lblNumeroRecepcao2 = new javax.swing.JLabel();
        txtChecksum2 = new javax.swing.JTextField();
        chkPSH2 = new javax.swing.JCheckBox();
        txtOptions2 = new javax.swing.JTextField();
        txtUrgentPointer2 = new javax.swing.JTextField();
        txtPortaOrigem2 = new javax.swing.JFormattedTextField();
        lblIpOrigem2 = new javax.swing.JLabel();
        lblPortaOrigem2 = new javax.swing.JLabel();
        txtIpOrigem2 = new javax.swing.JTextField();
        btnAceitar = new javax.swing.JButton();
        btnRecusar = new javax.swing.JButton();
        lblRecebendo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jInternalFrameMensagem = new javax.swing.JInternalFrame();
        pnlInternalFrameMensagem = new javax.swing.JPanel();
        txtMensagem = new javax.swing.JTextField();
        pnlParametros = new javax.swing.JPanel();
        lblQuantidadeDados = new javax.swing.JLabel();
        txtQuantidadeDados = new javax.swing.JTextField();
        sliderTamanhoJanela = new javax.swing.JSlider();
        lblTamanhoJanela = new javax.swing.JLabel();
        txtTamanhoJanela = new javax.swing.JFormattedTextField();
        sliderTamanhoMensagem = new javax.swing.JSlider();
        btnEnviar = new javax.swing.JButton();
        pnlPacoteEnvio = new javax.swing.JPanel();
        pnlDadosPacoteEnvio = new javax.swing.JPanel();
        txtIpDestino = new javax.swing.JFormattedTextField();
        lblIpDestino = new javax.swing.JLabel();
        lblPortaDestino = new javax.swing.JLabel();
        txtTamanhoDadosPacote = new javax.swing.JTextField();
        txtJanelaRecepcao = new javax.swing.JFormattedTextField();
        lblTamanhoDadosPacote = new javax.swing.JLabel();
        txtPortaDestino = new javax.swing.JFormattedTextField();
        lblJanelaRecepcao = new javax.swing.JLabel();
        lblTamanhoCabecalho = new javax.swing.JLabel();
        chkSYN = new javax.swing.JCheckBox();
        txtNumeroSequencia = new javax.swing.JFormattedTextField();
        chkACK = new javax.swing.JCheckBox();
        txtNumeroRecepcao = new javax.swing.JFormattedTextField();
        chkRST = new javax.swing.JCheckBox();
        chkFIN = new javax.swing.JCheckBox();
        lblChecksum = new javax.swing.JLabel();
        lblNumeroSequencia = new javax.swing.JLabel();
        lblUrgentPointer = new javax.swing.JLabel();
        chkURG = new javax.swing.JCheckBox();
        lblOptions = new javax.swing.JLabel();
        txtTamanhoCabecalho = new javax.swing.JTextField();
        lblNumeroRecepcao = new javax.swing.JLabel();
        txtChecksum = new javax.swing.JTextField();
        chkPSH = new javax.swing.JCheckBox();
        txtOptions = new javax.swing.JTextField();
        txtUrgentPointer = new javax.swing.JTextField();
        txtPortaOrigem = new javax.swing.JFormattedTextField();
        lblIpOrigem = new javax.swing.JLabel();
        lblPortaOrigem = new javax.swing.JLabel();
        txtIpOrigem = new javax.swing.JTextField();
        jProgressBarEnvio = new javax.swing.JProgressBar();
        btnConfirmaEnvio = new javax.swing.JButton();
        lblEnviando = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPrincipal.setLayout(null);

        pnlPacoteRecebe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 102, 0), 3));
        pnlPacoteRecebe.setMinimumSize(new java.awt.Dimension(400, 220));
        pnlPacoteRecebe.setLayout(null);

        pnlDadosPacoteRecebe.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        lblIpDestino2.setText("IP de Destino");

        lblPortaDestino2.setText("Porta Destino");

        lblTamanhoDadosPacote2.setText("Dados");

        lblJanelaRecepcao2.setText("Janela de Recepção");

        lblTamanhoCabecalho2.setText("Tamanho Cabeçalho");

        chkSYN2.setText("SYN");

        chkACK2.setText("ACK");

        chkRST2.setText("RST");

        chkFIN2.setText("FIN");

        lblChecksum2.setText("Checksum");

        lblNumeroSequencia2.setText("Nº de Sequência");

        lblUrgentPointer2.setText("<html>Urgent<br>Pointer");

        chkURG2.setText("URG");

        lblOptions2.setText("Options");

        lblNumeroRecepcao2.setText("Nº de Recepção");

        chkPSH2.setText("PSH");

        lblIpOrigem2.setText("IP de Origem");

        lblPortaOrigem2.setText("Porta Origem");

        txtIpOrigem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIpOrigem2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDadosPacoteRecebeLayout = new javax.swing.GroupLayout(pnlDadosPacoteRecebe);
        pnlDadosPacoteRecebe.setLayout(pnlDadosPacoteRecebeLayout);
        pnlDadosPacoteRecebeLayout.setHorizontalGroup(
            pnlDadosPacoteRecebeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosPacoteRecebeLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlDadosPacoteRecebeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDadosPacoteRecebeLayout.createSequentialGroup()
                        .addComponent(chkURG2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkPSH2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkSYN2)
                        .addGap(18, 18, 18)
                        .addComponent(lblTamanhoDadosPacote2))
                    .addGroup(pnlDadosPacoteRecebeLayout.createSequentialGroup()
                        .addComponent(chkACK2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkRST2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkFIN2)
                        .addGap(18, 18, 18)
                        .addComponent(txtTamanhoDadosPacote2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtChecksum2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtOptions2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUrgentPointer2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDadosPacoteRecebeLayout.createSequentialGroup()
                        .addGroup(pnlDadosPacoteRecebeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDadosPacoteRecebeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblIpOrigem2)
                                .addComponent(txtIpDestino2))
                            .addComponent(txtIpOrigem2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlDadosPacoteRecebeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lblPortaOrigem2)
                            .addComponent(txtPortaOrigem2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPortaDestino2)
                            .addComponent(txtPortaDestino2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlDadosPacoteRecebeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDadosPacoteRecebeLayout.createSequentialGroup()
                                .addGroup(pnlDadosPacoteRecebeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNumeroSequencia2)
                                    .addComponent(txtNumeroSequencia2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnlDadosPacoteRecebeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblJanelaRecepcao2)
                                    .addComponent(txtJanelaRecepcao2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlDadosPacoteRecebeLayout.createSequentialGroup()
                                .addGroup(pnlDadosPacoteRecebeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblChecksum2)
                                    .addGroup(pnlDadosPacoteRecebeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblNumeroRecepcao2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtNumeroRecepcao2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(pnlDadosPacoteRecebeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTamanhoCabecalho2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlDadosPacoteRecebeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(pnlDadosPacoteRecebeLayout.createSequentialGroup()
                                            .addComponent(lblOptions2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblUrgentPointer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(lblTamanhoCabecalho2, javax.swing.GroupLayout.Alignment.LEADING))))))
                    .addComponent(lblIpDestino2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDadosPacoteRecebeLayout.setVerticalGroup(
            pnlDadosPacoteRecebeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosPacoteRecebeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDadosPacoteRecebeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlDadosPacoteRecebeLayout.createSequentialGroup()
                        .addGroup(pnlDadosPacoteRecebeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPortaOrigem2)
                            .addComponent(lblNumeroSequencia2)
                            .addComponent(lblIpOrigem2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlDadosPacoteRecebeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDadosPacoteRecebeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtPortaOrigem2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNumeroSequencia2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtIpOrigem2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlDadosPacoteRecebeLayout.createSequentialGroup()
                        .addComponent(lblJanelaRecepcao2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtJanelaRecepcao2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnlDadosPacoteRecebeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDadosPacoteRecebeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDadosPacoteRecebeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIpDestino2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPortaDestino2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumeroRecepcao2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDadosPacoteRecebeLayout.createSequentialGroup()
                            .addGroup(pnlDadosPacoteRecebeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblPortaDestino2)
                                .addComponent(lblIpDestino2)
                                .addComponent(lblNumeroRecepcao2))
                            .addGap(26, 26, 26)))
                    .addGroup(pnlDadosPacoteRecebeLayout.createSequentialGroup()
                        .addComponent(lblTamanhoCabecalho2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTamanhoCabecalho2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pnlDadosPacoteRecebeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDadosPacoteRecebeLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(pnlDadosPacoteRecebeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkPSH2)
                            .addComponent(chkURG2)
                            .addComponent(chkSYN2)
                            .addComponent(lblTamanhoDadosPacote2)
                            .addComponent(lblChecksum2)
                            .addComponent(lblOptions2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlDadosPacoteRecebeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkACK2)
                            .addComponent(chkRST2)
                            .addGroup(pnlDadosPacoteRecebeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(chkFIN2)
                                .addComponent(txtTamanhoDadosPacote2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtChecksum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtOptions2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtUrgentPointer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDadosPacoteRecebeLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblUrgentPointer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pnlPacoteRecebe.add(pnlDadosPacoteRecebe);
        pnlDadosPacoteRecebe.setBounds(340, 30, 415, 190);

        btnAceitar.setForeground(new java.awt.Color(0, 204, 0));
        btnAceitar.setText("ACEITAR");
        btnAceitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceitarActionPerformed(evt);
            }
        });
        pnlPacoteRecebe.add(btnAceitar);
        btnAceitar.setBounds(40, 80, 77, 70);

        btnRecusar.setForeground(new java.awt.Color(255, 51, 51));
        btnRecusar.setText("RECUSAR");
        pnlPacoteRecebe.add(btnRecusar);
        btnRecusar.setBounds(140, 80, 79, 70);

        lblRecebendo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblRecebendo.setForeground(new java.awt.Color(204, 102, 0));
        lblRecebendo.setText("Recebendo");
        pnlPacoteRecebe.add(lblRecebendo);
        lblRecebendo.setBounds(670, 10, 81, 17);

        pnlPrincipal.add(pnlPacoteRecebe);
        pnlPacoteRecebe.setBounds(10, 307, 770, 230);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Segmento 1", "Segmento 2", "Segmento 3", "Segmento 4", "Segmento 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        pnlPrincipal.add(jScrollPane1);
        jScrollPane1.setBounds(885, 34, 105, 287);

        jInternalFrameMensagem.setVisible(true);

        pnlInternalFrameMensagem.setLayout(null);

        txtMensagem.setText("Escreva sua Mensagem Aqui");
        pnlInternalFrameMensagem.add(txtMensagem);
        txtMensagem.setBounds(20, 40, 250, 80);

        pnlParametros.setBorder(javax.swing.BorderFactory.createTitledBorder("Parâmetros"));

        lblQuantidadeDados.setText("Quantidade de Dados");
        lblQuantidadeDados.setToolTipText("Deslize a barra para aumentar ou diminuir o tamanho");

        txtQuantidadeDados.setEditable(false);
        txtQuantidadeDados.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtQuantidadeDados.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtQuantidadeDados.setCaretPosition(0);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, sliderTamanhoMensagem, org.jdesktop.beansbinding.ELProperty.create("${value}"), txtQuantidadeDados, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        sliderTamanhoJanela.setMaximum(300);
        sliderTamanhoJanela.setToolTipText("");
        sliderTamanhoJanela.setValue(150);

        lblTamanhoJanela.setText("Tamanho da Janela");
        lblTamanhoJanela.setToolTipText("Deslize a barra para aumentar ou diminuir o tamanho");

        sliderTamanhoMensagem.setMaximum(300);
        sliderTamanhoMensagem.setToolTipText("");
        sliderTamanhoMensagem.setValue(150);

        javax.swing.GroupLayout pnlParametrosLayout = new javax.swing.GroupLayout(pnlParametros);
        pnlParametros.setLayout(pnlParametrosLayout);
        pnlParametrosLayout.setHorizontalGroup(
            pnlParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlParametrosLayout.createSequentialGroup()
                .addGroup(pnlParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQuantidadeDados)
                    .addComponent(lblTamanhoJanela))
                .addGap(18, 18, 18)
                .addGroup(pnlParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtQuantidadeDados, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTamanhoJanela, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlParametrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sliderTamanhoMensagem, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(sliderTamanhoJanela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        pnlParametrosLayout.setVerticalGroup(
            pnlParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlParametrosLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnlParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtQuantidadeDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQuantidadeDados))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sliderTamanhoMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(pnlParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTamanhoJanela)
                    .addComponent(txtTamanhoJanela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sliderTamanhoJanela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlInternalFrameMensagem.add(pnlParametros);
        pnlParametros.setBounds(300, 20, 290, 210);

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        pnlInternalFrameMensagem.add(btnEnviar);
        btnEnviar.setBounds(90, 170, 120, 50);

        javax.swing.GroupLayout jInternalFrameMensagemLayout = new javax.swing.GroupLayout(jInternalFrameMensagem.getContentPane());
        jInternalFrameMensagem.getContentPane().setLayout(jInternalFrameMensagemLayout);
        jInternalFrameMensagemLayout.setHorizontalGroup(
            jInternalFrameMensagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlInternalFrameMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jInternalFrameMensagemLayout.setVerticalGroup(
            jInternalFrameMensagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlInternalFrameMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jDesktopPane1.add(jInternalFrameMensagem);
        jInternalFrameMensagem.setBounds(190, 90, 627, 416);

        pnlPacoteEnvio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 3));
        pnlPacoteEnvio.setMinimumSize(new java.awt.Dimension(400, 220));
        pnlPacoteEnvio.setLayout(null);

        pnlDadosPacoteEnvio.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        lblIpDestino.setText("IP de Destino");

        lblPortaDestino.setText("Porta Destino");

        lblTamanhoDadosPacote.setText("Dados");

        lblJanelaRecepcao.setText("Janela de Recepção");

        lblTamanhoCabecalho.setText("Tamanho Cabeçalho");

        chkSYN.setText("SYN");

        chkACK.setText("ACK");

        chkRST.setText("RST");

        chkFIN.setText("FIN");
        chkFIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkFINActionPerformed(evt);
            }
        });

        lblChecksum.setText("Checksum");

        lblNumeroSequencia.setText("Nº de Sequência");

        lblUrgentPointer.setText("<html>Urgent<br>Pointer");

        chkURG.setText("URG");

        lblOptions.setText("Options");

        lblNumeroRecepcao.setText("Nº de Recepção");

        chkPSH.setText("PSH");

        lblIpOrigem.setText("IP de Origem");

        lblPortaOrigem.setText("Porta Origem");

        txtIpOrigem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIpOrigemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDadosPacoteEnvioLayout = new javax.swing.GroupLayout(pnlDadosPacoteEnvio);
        pnlDadosPacoteEnvio.setLayout(pnlDadosPacoteEnvioLayout);
        pnlDadosPacoteEnvioLayout.setHorizontalGroup(
            pnlDadosPacoteEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosPacoteEnvioLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlDadosPacoteEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDadosPacoteEnvioLayout.createSequentialGroup()
                        .addComponent(chkURG)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkPSH)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkSYN)
                        .addGap(18, 18, 18)
                        .addComponent(lblTamanhoDadosPacote))
                    .addGroup(pnlDadosPacoteEnvioLayout.createSequentialGroup()
                        .addComponent(chkACK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkRST)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkFIN)
                        .addGap(18, 18, 18)
                        .addComponent(txtTamanhoDadosPacote, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtChecksum, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUrgentPointer, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDadosPacoteEnvioLayout.createSequentialGroup()
                        .addGroup(pnlDadosPacoteEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDadosPacoteEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblIpOrigem)
                                .addComponent(txtIpDestino))
                            .addComponent(txtIpOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlDadosPacoteEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lblPortaOrigem)
                            .addComponent(txtPortaOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPortaDestino)
                            .addComponent(txtPortaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlDadosPacoteEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDadosPacoteEnvioLayout.createSequentialGroup()
                                .addGroup(pnlDadosPacoteEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNumeroSequencia)
                                    .addComponent(txtNumeroSequencia, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnlDadosPacoteEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblJanelaRecepcao)
                                    .addComponent(txtJanelaRecepcao, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlDadosPacoteEnvioLayout.createSequentialGroup()
                                .addGroup(pnlDadosPacoteEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblChecksum)
                                    .addGroup(pnlDadosPacoteEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblNumeroRecepcao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtNumeroRecepcao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(pnlDadosPacoteEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTamanhoCabecalho, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlDadosPacoteEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(pnlDadosPacoteEnvioLayout.createSequentialGroup()
                                            .addComponent(lblOptions)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblUrgentPointer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(lblTamanhoCabecalho, javax.swing.GroupLayout.Alignment.LEADING))))))
                    .addComponent(lblIpDestino))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDadosPacoteEnvioLayout.setVerticalGroup(
            pnlDadosPacoteEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosPacoteEnvioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDadosPacoteEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlDadosPacoteEnvioLayout.createSequentialGroup()
                        .addGroup(pnlDadosPacoteEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPortaOrigem)
                            .addComponent(lblNumeroSequencia)
                            .addComponent(lblIpOrigem))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlDadosPacoteEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDadosPacoteEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtPortaOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNumeroSequencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtIpOrigem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlDadosPacoteEnvioLayout.createSequentialGroup()
                        .addComponent(lblJanelaRecepcao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtJanelaRecepcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnlDadosPacoteEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDadosPacoteEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDadosPacoteEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIpDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPortaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumeroRecepcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDadosPacoteEnvioLayout.createSequentialGroup()
                            .addGroup(pnlDadosPacoteEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblPortaDestino)
                                .addComponent(lblIpDestino)
                                .addComponent(lblNumeroRecepcao))
                            .addGap(26, 26, 26)))
                    .addGroup(pnlDadosPacoteEnvioLayout.createSequentialGroup()
                        .addComponent(lblTamanhoCabecalho)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTamanhoCabecalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pnlDadosPacoteEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDadosPacoteEnvioLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(pnlDadosPacoteEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkPSH)
                            .addComponent(chkURG)
                            .addComponent(chkSYN)
                            .addComponent(lblTamanhoDadosPacote)
                            .addComponent(lblChecksum)
                            .addComponent(lblOptions))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlDadosPacoteEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkACK)
                            .addComponent(chkRST)
                            .addGroup(pnlDadosPacoteEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(chkFIN)
                                .addComponent(txtTamanhoDadosPacote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtChecksum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtUrgentPointer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDadosPacoteEnvioLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblUrgentPointer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlPacoteEnvio.add(pnlDadosPacoteEnvio);
        pnlDadosPacoteEnvio.setBounds(10, 30, 415, 180);
        pnlPacoteEnvio.add(jProgressBarEnvio);
        jProgressBarEnvio.setBounds(470, 80, 280, 23);

        btnConfirmaEnvio.setBackground(new java.awt.Color(0, 255, 0));
        btnConfirmaEnvio.setText("Segmento Confirmado");
        pnlPacoteEnvio.add(btnConfirmaEnvio);
        btnConfirmaEnvio.setBounds(530, 100, 174, 42);

        lblEnviando.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEnviando.setForeground(new java.awt.Color(0, 153, 153));
        lblEnviando.setText("Enviando");
        pnlPacoteEnvio.add(lblEnviando);
        lblEnviando.setBounds(20, 10, 81, 17);

        jDesktopPane1.add(pnlPacoteEnvio);
        pnlPacoteEnvio.setBounds(-10, -130, 770, 230);

        pnlPrincipal.add(jDesktopPane1);
        jDesktopPane1.setBounds(0, 0, 1000, 560);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        setSize(new java.awt.Dimension(1016, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtIpOrigemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIpOrigemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIpOrigemActionPerformed

    private void txtIpOrigem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIpOrigem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIpOrigem2ActionPerformed

    private void btnAceitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceitarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAceitarActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        
        mensagem = new Mensagem();
        mensagem.setTexto(txtMensagem.getText());

        pnlPacoteEnvio.setVisible(true);
        txtIpOrigem.setText(IpOrigem);
        txtIpDestino.setText(IpDestino);

    }//GEN-LAST:event_btnEnviarActionPerformed

    private void chkFINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkFINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkFINActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnvioDeMensagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnvioDeMensagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnvioDeMensagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnvioDeMensagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnvioDeMensagens().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceitar;
    private javax.swing.JButton btnConfirmaEnvio;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnRecusar;
    private javax.swing.JCheckBox chkACK;
    private javax.swing.JCheckBox chkACK2;
    private javax.swing.JCheckBox chkFIN;
    private javax.swing.JCheckBox chkFIN2;
    private javax.swing.JCheckBox chkPSH;
    private javax.swing.JCheckBox chkPSH2;
    private javax.swing.JCheckBox chkRST;
    private javax.swing.JCheckBox chkRST2;
    private javax.swing.JCheckBox chkSYN;
    private javax.swing.JCheckBox chkSYN2;
    private javax.swing.JCheckBox chkURG;
    private javax.swing.JCheckBox chkURG2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JInternalFrame jInternalFrameMensagem;
    private javax.swing.JList<String> jList1;
    private javax.swing.JProgressBar jProgressBarEnvio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblChecksum;
    private javax.swing.JLabel lblChecksum2;
    private javax.swing.JLabel lblEnviando;
    private javax.swing.JLabel lblIpDestino;
    private javax.swing.JLabel lblIpDestino2;
    private javax.swing.JLabel lblIpOrigem;
    private javax.swing.JLabel lblIpOrigem2;
    private javax.swing.JLabel lblJanelaRecepcao;
    private javax.swing.JLabel lblJanelaRecepcao2;
    private javax.swing.JLabel lblNumeroRecepcao;
    private javax.swing.JLabel lblNumeroRecepcao2;
    private javax.swing.JLabel lblNumeroSequencia;
    private javax.swing.JLabel lblNumeroSequencia2;
    private javax.swing.JLabel lblOptions;
    private javax.swing.JLabel lblOptions2;
    private javax.swing.JLabel lblPortaDestino;
    private javax.swing.JLabel lblPortaDestino2;
    private javax.swing.JLabel lblPortaOrigem;
    private javax.swing.JLabel lblPortaOrigem2;
    private javax.swing.JLabel lblQuantidadeDados;
    private javax.swing.JLabel lblRecebendo;
    private javax.swing.JLabel lblTamanhoCabecalho;
    private javax.swing.JLabel lblTamanhoCabecalho2;
    private javax.swing.JLabel lblTamanhoDadosPacote;
    private javax.swing.JLabel lblTamanhoDadosPacote2;
    private javax.swing.JLabel lblTamanhoJanela;
    private javax.swing.JLabel lblUrgentPointer;
    private javax.swing.JLabel lblUrgentPointer2;
    private javax.swing.JPanel pnlDadosPacoteEnvio;
    private javax.swing.JPanel pnlDadosPacoteRecebe;
    private javax.swing.JPanel pnlInternalFrameMensagem;
    private javax.swing.JPanel pnlPacoteEnvio;
    private javax.swing.JPanel pnlPacoteRecebe;
    private javax.swing.JPanel pnlParametros;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JSlider sliderTamanhoJanela;
    private javax.swing.JSlider sliderTamanhoMensagem;
    private javax.swing.JTextField txtChecksum;
    private javax.swing.JTextField txtChecksum2;
    private javax.swing.JFormattedTextField txtIpDestino;
    private javax.swing.JFormattedTextField txtIpDestino2;
    private javax.swing.JTextField txtIpOrigem;
    private javax.swing.JTextField txtIpOrigem2;
    private javax.swing.JFormattedTextField txtJanelaRecepcao;
    private javax.swing.JFormattedTextField txtJanelaRecepcao2;
    private javax.swing.JTextField txtMensagem;
    private javax.swing.JFormattedTextField txtNumeroRecepcao;
    private javax.swing.JFormattedTextField txtNumeroRecepcao2;
    private javax.swing.JFormattedTextField txtNumeroSequencia;
    private javax.swing.JFormattedTextField txtNumeroSequencia2;
    private javax.swing.JTextField txtOptions;
    private javax.swing.JTextField txtOptions2;
    private javax.swing.JFormattedTextField txtPortaDestino;
    private javax.swing.JFormattedTextField txtPortaDestino2;
    private javax.swing.JFormattedTextField txtPortaOrigem;
    private javax.swing.JFormattedTextField txtPortaOrigem2;
    private javax.swing.JTextField txtQuantidadeDados;
    private javax.swing.JTextField txtTamanhoCabecalho;
    private javax.swing.JTextField txtTamanhoCabecalho2;
    private javax.swing.JTextField txtTamanhoDadosPacote;
    private javax.swing.JTextField txtTamanhoDadosPacote2;
    private javax.swing.JFormattedTextField txtTamanhoJanela;
    private javax.swing.JTextField txtUrgentPointer;
    private javax.swing.JTextField txtUrgentPointer2;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    public String getIpOrigem() {
        return IpOrigem;
    }

    public void setIpOrigem(String IpOrigem) {
        this.IpOrigem = IpOrigem;
    }

    public String getIpDestino() {
        return IpDestino;
    }

    public void setIpDestino(String IpDestino) {
        this.IpDestino = IpDestino;
    }

}
