/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

/**
 *
 * @author LORD
 */
public class Pacote extends javax.swing.JInternalFrame {

    /**
     * Creates new form Pacote
     */
    public Pacote() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlComunicacao2 = new javax.swing.JPanel();
        pnlSegmento2 = new javax.swing.JPanel();
        txtIpDestino3 = new javax.swing.JFormattedTextField();
        lblIpDestino4 = new javax.swing.JLabel();
        lblPortaDestino4 = new javax.swing.JLabel();
        txtTamanhoDadosPacote3 = new javax.swing.JTextField();
        txtJanelaRecepcao3 = new javax.swing.JFormattedTextField();
        lblTamanhoDadosPacote4 = new javax.swing.JLabel();
        txtPortaDestino3 = new javax.swing.JFormattedTextField();
        lblJanelaRecepcao4 = new javax.swing.JLabel();
        lblTamanhoCabecalho4 = new javax.swing.JLabel();
        chkSYN3 = new javax.swing.JCheckBox();
        txtNumeroSequencia3 = new javax.swing.JFormattedTextField();
        chkACK3 = new javax.swing.JCheckBox();
        txtNumeroRecepcao3 = new javax.swing.JFormattedTextField();
        chkRST3 = new javax.swing.JCheckBox();
        chkFIN3 = new javax.swing.JCheckBox();
        lblChecksum4 = new javax.swing.JLabel();
        lblNumeroSequencia4 = new javax.swing.JLabel();
        lblUrgentPointer4 = new javax.swing.JLabel();
        chkURG3 = new javax.swing.JCheckBox();
        lblOptions4 = new javax.swing.JLabel();
        txtTamanhoCabecalho3 = new javax.swing.JTextField();
        lblNumeroRecepcao4 = new javax.swing.JLabel();
        txtChecksum3 = new javax.swing.JTextField();
        chkPSH3 = new javax.swing.JCheckBox();
        txtOptions3 = new javax.swing.JTextField();
        txtUrgentPointer3 = new javax.swing.JTextField();
        txtPortaOrigem3 = new javax.swing.JFormattedTextField();
        lblIpOrigem5 = new javax.swing.JLabel();
        lblPortaOrigem4 = new javax.swing.JLabel();
        txtIpOrigem3 = new javax.swing.JTextField();
        btnAceitar1 = new javax.swing.JButton();
        btnRecusar1 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        btnConfirmaEnvio1 = new javax.swing.JButton();

        setBorder(null);

        pnlComunicacao2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        pnlComunicacao2.setMinimumSize(new java.awt.Dimension(400, 220));

        pnlSegmento2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        lblIpDestino4.setText("IP de Destino");

        lblPortaDestino4.setText("Porta Destino");

        lblTamanhoDadosPacote4.setText("Dados");

        lblJanelaRecepcao4.setText("Janela de Recepção");

        lblTamanhoCabecalho4.setText("Tamanho Cabeçalho");

        chkSYN3.setText("SYN");

        chkACK3.setText("ACK");

        chkRST3.setText("RST");

        chkFIN3.setText("FIN");

        lblChecksum4.setText("Checksum");

        lblNumeroSequencia4.setText("Nº de Sequência");

        lblUrgentPointer4.setText("<html>Urgent<br>Pointer");

        chkURG3.setText("URG");

        lblOptions4.setText("Options");

        lblNumeroRecepcao4.setText("Nº de Recepção");

        chkPSH3.setText("PSH");

        lblIpOrigem5.setText("IP de Origem");

        lblPortaOrigem4.setText("Porta Origem");

        txtIpOrigem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIpOrigem3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSegmento2Layout = new javax.swing.GroupLayout(pnlSegmento2);
        pnlSegmento2.setLayout(pnlSegmento2Layout);
        pnlSegmento2Layout.setHorizontalGroup(
            pnlSegmento2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSegmento2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlSegmento2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSegmento2Layout.createSequentialGroup()
                        .addComponent(chkURG3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkPSH3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkSYN3)
                        .addGap(18, 18, 18)
                        .addComponent(lblTamanhoDadosPacote4))
                    .addGroup(pnlSegmento2Layout.createSequentialGroup()
                        .addComponent(chkACK3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkRST3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkFIN3)
                        .addGap(18, 18, 18)
                        .addComponent(txtTamanhoDadosPacote3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtChecksum3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtOptions3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUrgentPointer3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlSegmento2Layout.createSequentialGroup()
                        .addGroup(pnlSegmento2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlSegmento2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblIpOrigem5)
                                .addComponent(txtIpDestino3))
                            .addComponent(txtIpOrigem3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlSegmento2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lblPortaOrigem4)
                            .addComponent(txtPortaOrigem3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPortaDestino4)
                            .addComponent(txtPortaDestino3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlSegmento2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlSegmento2Layout.createSequentialGroup()
                                .addGroup(pnlSegmento2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNumeroSequencia4)
                                    .addComponent(txtNumeroSequencia3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnlSegmento2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblJanelaRecepcao4)
                                    .addComponent(txtJanelaRecepcao3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlSegmento2Layout.createSequentialGroup()
                                .addGroup(pnlSegmento2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblChecksum4)
                                    .addGroup(pnlSegmento2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblNumeroRecepcao4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtNumeroRecepcao3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(pnlSegmento2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTamanhoCabecalho3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlSegmento2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(pnlSegmento2Layout.createSequentialGroup()
                                            .addComponent(lblOptions4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblUrgentPointer4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(lblTamanhoCabecalho4, javax.swing.GroupLayout.Alignment.LEADING))))))
                    .addComponent(lblIpDestino4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSegmento2Layout.setVerticalGroup(
            pnlSegmento2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSegmento2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSegmento2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlSegmento2Layout.createSequentialGroup()
                        .addGroup(pnlSegmento2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPortaOrigem4)
                            .addComponent(lblNumeroSequencia4)
                            .addComponent(lblIpOrigem5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlSegmento2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlSegmento2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtPortaOrigem3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNumeroSequencia3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtIpOrigem3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlSegmento2Layout.createSequentialGroup()
                        .addComponent(lblJanelaRecepcao4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtJanelaRecepcao3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnlSegmento2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSegmento2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSegmento2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIpDestino3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPortaDestino3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumeroRecepcao3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSegmento2Layout.createSequentialGroup()
                            .addGroup(pnlSegmento2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblPortaDestino4)
                                .addComponent(lblIpDestino4)
                                .addComponent(lblNumeroRecepcao4))
                            .addGap(26, 26, 26)))
                    .addGroup(pnlSegmento2Layout.createSequentialGroup()
                        .addComponent(lblTamanhoCabecalho4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTamanhoCabecalho3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pnlSegmento2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlSegmento2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(pnlSegmento2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkPSH3)
                            .addComponent(chkURG3)
                            .addComponent(chkSYN3)
                            .addComponent(lblTamanhoDadosPacote4)
                            .addComponent(lblChecksum4)
                            .addComponent(lblOptions4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlSegmento2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkACK3)
                            .addComponent(chkRST3)
                            .addGroup(pnlSegmento2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(chkFIN3)
                                .addComponent(txtTamanhoDadosPacote3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtChecksum3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtOptions3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtUrgentPointer3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlSegmento2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblUrgentPointer4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAceitar1.setForeground(new java.awt.Color(0, 204, 0));
        btnAceitar1.setText("ACEITAR");
        btnAceitar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceitar1ActionPerformed(evt);
            }
        });

        btnRecusar1.setForeground(new java.awt.Color(255, 51, 51));
        btnRecusar1.setText("RECUSAR");

        btnConfirmaEnvio1.setBackground(new java.awt.Color(0, 255, 0));
        btnConfirmaEnvio1.setText("Segmento Confirmado");

        javax.swing.GroupLayout pnlComunicacao2Layout = new javax.swing.GroupLayout(pnlComunicacao2);
        pnlComunicacao2.setLayout(pnlComunicacao2Layout);
        pnlComunicacao2Layout.setHorizontalGroup(
            pnlComunicacao2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlComunicacao2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlSegmento2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(pnlComunicacao2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlComunicacao2Layout.createSequentialGroup()
                        .addComponent(btnAceitar1)
                        .addGap(18, 18, 18)
                        .addComponent(btnRecusar1))
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConfirmaEnvio1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        pnlComunicacao2Layout.setVerticalGroup(
            pnlComunicacao2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlComunicacao2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(pnlComunicacao2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceitar1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRecusar1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConfirmaEnvio1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlComunicacao2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(pnlSegmento2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlComunicacao2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlComunicacao2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIpOrigem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIpOrigem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIpOrigem3ActionPerformed

    private void btnAceitar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceitar1ActionPerformed
    }//GEN-LAST:event_btnAceitar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceitar1;
    private javax.swing.JButton btnConfirmaEnvio1;
    private javax.swing.JButton btnRecusar1;
    private javax.swing.JCheckBox chkACK1;
    private javax.swing.JCheckBox chkACK2;
    private javax.swing.JCheckBox chkACK3;
    private javax.swing.JCheckBox chkFIN1;
    private javax.swing.JCheckBox chkFIN2;
    private javax.swing.JCheckBox chkFIN3;
    private javax.swing.JCheckBox chkPSH1;
    private javax.swing.JCheckBox chkPSH2;
    private javax.swing.JCheckBox chkPSH3;
    private javax.swing.JCheckBox chkRST1;
    private javax.swing.JCheckBox chkRST2;
    private javax.swing.JCheckBox chkRST3;
    private javax.swing.JCheckBox chkSYN1;
    private javax.swing.JCheckBox chkSYN2;
    private javax.swing.JCheckBox chkSYN3;
    private javax.swing.JCheckBox chkURG1;
    private javax.swing.JCheckBox chkURG2;
    private javax.swing.JCheckBox chkURG3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel lblChecksum2;
    private javax.swing.JLabel lblChecksum3;
    private javax.swing.JLabel lblChecksum4;
    private javax.swing.JLabel lblIpDestino2;
    private javax.swing.JLabel lblIpDestino3;
    private javax.swing.JLabel lblIpDestino4;
    private javax.swing.JLabel lblIpOrigem3;
    private javax.swing.JLabel lblIpOrigem4;
    private javax.swing.JLabel lblIpOrigem5;
    private javax.swing.JLabel lblJanelaRecepcao2;
    private javax.swing.JLabel lblJanelaRecepcao3;
    private javax.swing.JLabel lblJanelaRecepcao4;
    private javax.swing.JLabel lblNumeroRecepcao2;
    private javax.swing.JLabel lblNumeroRecepcao3;
    private javax.swing.JLabel lblNumeroRecepcao4;
    private javax.swing.JLabel lblNumeroSequencia2;
    private javax.swing.JLabel lblNumeroSequencia3;
    private javax.swing.JLabel lblNumeroSequencia4;
    private javax.swing.JLabel lblOptions2;
    private javax.swing.JLabel lblOptions3;
    private javax.swing.JLabel lblOptions4;
    private javax.swing.JLabel lblPortaDestino2;
    private javax.swing.JLabel lblPortaDestino3;
    private javax.swing.JLabel lblPortaDestino4;
    private javax.swing.JLabel lblPortaOrigem2;
    private javax.swing.JLabel lblPortaOrigem3;
    private javax.swing.JLabel lblPortaOrigem4;
    private javax.swing.JLabel lblTamanhoCabecalho2;
    private javax.swing.JLabel lblTamanhoCabecalho3;
    private javax.swing.JLabel lblTamanhoCabecalho4;
    private javax.swing.JLabel lblTamanhoDadosPacote2;
    private javax.swing.JLabel lblTamanhoDadosPacote3;
    private javax.swing.JLabel lblTamanhoDadosPacote4;
    private javax.swing.JLabel lblUrgentPointer2;
    private javax.swing.JLabel lblUrgentPointer3;
    private javax.swing.JLabel lblUrgentPointer4;
    private javax.swing.JPanel pnlComunicacao;
    private javax.swing.JPanel pnlComunicacao1;
    private javax.swing.JPanel pnlComunicacao2;
    private javax.swing.JPanel pnlSegmento;
    private javax.swing.JPanel pnlSegmento1;
    private javax.swing.JPanel pnlSegmento2;
    private javax.swing.JTextField txtChecksum1;
    private javax.swing.JTextField txtChecksum2;
    private javax.swing.JTextField txtChecksum3;
    private javax.swing.JFormattedTextField txtIpDestino1;
    private javax.swing.JFormattedTextField txtIpDestino2;
    private javax.swing.JFormattedTextField txtIpDestino3;
    private javax.swing.JTextField txtIpOrigem1;
    private javax.swing.JTextField txtIpOrigem2;
    private javax.swing.JTextField txtIpOrigem3;
    private javax.swing.JFormattedTextField txtJanelaRecepcao1;
    private javax.swing.JFormattedTextField txtJanelaRecepcao2;
    private javax.swing.JFormattedTextField txtJanelaRecepcao3;
    private javax.swing.JFormattedTextField txtNumeroRecepcao1;
    private javax.swing.JFormattedTextField txtNumeroRecepcao2;
    private javax.swing.JFormattedTextField txtNumeroRecepcao3;
    private javax.swing.JFormattedTextField txtNumeroSequencia1;
    private javax.swing.JFormattedTextField txtNumeroSequencia2;
    private javax.swing.JFormattedTextField txtNumeroSequencia3;
    private javax.swing.JTextField txtOptions1;
    private javax.swing.JTextField txtOptions2;
    private javax.swing.JTextField txtOptions3;
    private javax.swing.JFormattedTextField txtPortaDestino1;
    private javax.swing.JFormattedTextField txtPortaDestino2;
    private javax.swing.JFormattedTextField txtPortaDestino3;
    private javax.swing.JFormattedTextField txtPortaOrigem1;
    private javax.swing.JFormattedTextField txtPortaOrigem2;
    private javax.swing.JFormattedTextField txtPortaOrigem3;
    private javax.swing.JTextField txtTamanhoCabecalho1;
    private javax.swing.JTextField txtTamanhoCabecalho2;
    private javax.swing.JTextField txtTamanhoCabecalho3;
    private javax.swing.JTextField txtTamanhoDadosPacote1;
    private javax.swing.JTextField txtTamanhoDadosPacote2;
    private javax.swing.JTextField txtTamanhoDadosPacote3;
    private javax.swing.JTextField txtUrgentPointer1;
    private javax.swing.JTextField txtUrgentPointer2;
    private javax.swing.JTextField txtUrgentPointer3;
    // End of variables declaration//GEN-END:variables
}
