/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import aplicacao.Mensagem;
import aplicacao.Mensagem.Action;
import aplicacao.Pacote;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.ObjectInputStream;
import java.net.InetAddress;
import java.net.Socket;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.JTextField;
import service.ClienteService;
import static javax.swing.JOptionPane.showMessageDialog;
import static javax.swing.JOptionPane.showMessageDialog;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author Lord
 */
public class TelaParametros extends javax.swing.JFrame {

    private Mensagem mensagem;
    private ClienteService service;

    public String getTxtNumeroSequencia() {
        return txtNumeroSequencia.getText();
    }

    public void setTxtNumeroSequencia(String txtNumeroSequencia) {
        this.txtNumeroSequencia.setText(txtNumeroSequencia);
    }
    
    

    public TelaParametros(Mensagem mensagem) {
        
        initComponents();
        
        this.mensagem = mensagem;
        txtIpOrigem.setText(mensagem.getIpOrigem());
        txtIpDestino.setText(mensagem.getIpDestino());
        verificarId(mensagem);
        txtMensagem.setEnabled(false);
        //txtNumeroSequencia.setText(String.valueOf(mensagem.getPacotes().get(0).getNumeroSequencia()));
        
    }

    private TelaParametros() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private class ListenerSocket implements Runnable {

        private ObjectInputStream input;

        public ListenerSocket(Socket socket) {

            try {

                this.input = new ObjectInputStream(socket.getInputStream());

            } catch (IOException ex) {
                Logger.getLogger(TelaParametros.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        @Override
        public void run() {
            Mensagem mensagem = null;

            try {
                while ((mensagem = (Mensagem) input.readObject()) != null) {

                    Action action = mensagem.getAction();
                    
                    if (action.equals(Action.CONECTAR)) {
                        //Qdo clicar em enviar mensagem e o ID da mensagem for igual a 1
                        conectar(mensagem);
                        
                    } else if (action.equals(Action.DISCONECTAR)) {
                        disconectar(mensagem);
                        
                    } else if (action.equals(Action.ENVIAR)) {
                        enviar(mensagem);
                        
                    } else if (action.equals(Action.USUARIOS_ONLINE)) {
                        usuariosOnline(mensagem);
                        
                    }
                }
            } catch (IOException ex) {
                Logger.getLogger(TelaParametros.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(TelaParametros.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }
    
    private void conectar(Mensagem mensagem){
        
    }
    
    private void disconectar(Mensagem mensagem){
        
    }
    
    private void enviar(Mensagem mensagem){
        this.mensagem = mensagem;
    }
    
    private void usuariosOnline(Mensagem mensagem){
        
    }
    
    private void verificarId(Mensagem mensagem){
        
        if(mensagem.getIdMensagem() == 1){

            chkSYN.setSelected(true);
            chkFIN.setEnabled(false);
            chkACK.setEnabled(false);
            chkPSH.setEnabled(false);
            chkRST.setEnabled(false);
            chkURG.setEnabled(false);
            
        }
        
    }
    

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        sliderTamanhoMensagem = new javax.swing.JSlider();
        lblTamanhoMensagem = new javax.swing.JLabel();
        txtTamanhoMensagem = new javax.swing.JTextField();
        txtMensagem = new javax.swing.JTextField();
        lblMensagem = new javax.swing.JLabel();
        lblMegaBytes = new javax.swing.JLabel();
        txtIpOrigem = new javax.swing.JFormattedTextField();
        lblIpOrigem = new javax.swing.JLabel();
        txtIpDestino = new javax.swing.JFormattedTextField();
        lblIpDestino = new javax.swing.JLabel();
        txtJanelaRecepcao = new javax.swing.JFormattedTextField();
        lblJanelaRecepcao = new javax.swing.JLabel();
        lblNumeroSequencia = new javax.swing.JLabel();
        lblNumeroRecepcao = new javax.swing.JLabel();
        lblPortaOrigem = new javax.swing.JLabel();
        lblPortaDestino = new javax.swing.JLabel();
        txtPortaDestino = new javax.swing.JFormattedTextField();
        txtNumeroRecepcao = new javax.swing.JFormattedTextField();
        chkSYN = new javax.swing.JCheckBox();
        chkFIN = new javax.swing.JCheckBox();
        txtPortaOrigem = new javax.swing.JFormattedTextField();
        btnEnviar = new javax.swing.JButton();
        chkURG = new javax.swing.JCheckBox();
        chkPSH = new javax.swing.JCheckBox();
        chkACK = new javax.swing.JCheckBox();
        chkRST = new javax.swing.JCheckBox();
        txtNumeroSequencia = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sliderTamanhoMensagem.setMaximum(300);
        sliderTamanhoMensagem.setToolTipText("");
        sliderTamanhoMensagem.setValue(150);

        lblTamanhoMensagem.setText("Tamanho da Mensagem");
        lblTamanhoMensagem.setToolTipText("Deslize a barra para aumentar ou diminuir o tamanho");

        txtTamanhoMensagem.setEditable(false);
        txtTamanhoMensagem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtTamanhoMensagem.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, sliderTamanhoMensagem, org.jdesktop.beansbinding.ELProperty.create("${value}"), txtTamanhoMensagem, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        txtTamanhoMensagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTamanhoMensagemActionPerformed(evt);
            }
        });

        lblMensagem.setText("Mensagem");
        lblMensagem.setToolTipText("");

        lblMegaBytes.setText("MB");

        txtIpOrigem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIpOrigemActionPerformed(evt);
            }
        });

        lblIpOrigem.setText("IP de Origem");

        lblIpDestino.setText("IP de Destino");

        lblJanelaRecepcao.setText("Janela de Recepção");

        lblNumeroSequencia.setText("Número de Sequência");

        lblNumeroRecepcao.setText("Número de Recepção");

        lblPortaOrigem.setText("Porta de Origem");

        lblPortaDestino.setText("Porta de Destino");

        txtPortaDestino.setEditable(false);
        txtPortaDestino.setText("5000");

        chkSYN.setText("SYN");

        chkFIN.setText("FIN");

        txtPortaOrigem.setEditable(false);
        txtPortaOrigem.setText("5000");

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        chkURG.setText("URG");

        chkPSH.setText("PSH");

        chkACK.setText("ACK");

        chkRST.setText("RST");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblMensagem)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIpOrigem)
                            .addComponent(txtIpOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lblPortaOrigem)
                            .addComponent(txtPortaOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPortaDestino)
                            .addComponent(txtPortaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblNumeroSequencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNumeroSequencia)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIpDestino)
                            .addComponent(txtIpDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtJanelaRecepcao, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblJanelaRecepcao))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chkACK)
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(lblNumeroRecepcao)
                                    .addComponent(txtNumeroRecepcao, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(chkURG)
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkPSH)
                                    .addComponent(chkRST))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkFIN)
                                    .addComponent(chkSYN)))))
                    .addComponent(sliderTamanhoMensagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTamanhoMensagem)
                        .addGap(18, 18, 18)
                        .addComponent(txtTamanhoMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMegaBytes)))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPortaOrigem)
                    .addComponent(lblNumeroSequencia)
                    .addComponent(lblIpOrigem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIpOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPortaOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroSequencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIpDestino, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPortaDestino)
                            .addComponent(lblIpDestino)
                            .addComponent(lblNumeroRecepcao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumeroRecepcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPortaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblJanelaRecepcao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtJanelaRecepcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkSYN)
                            .addComponent(chkPSH))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkRST)
                            .addComponent(chkFIN)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkURG)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkACK)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTamanhoMensagem)
                    .addComponent(txtTamanhoMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMegaBytes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sliderTamanhoMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblMensagem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
              
            this.service.enviar(mensagem);
            
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void txtIpOrigemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIpOrigemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIpOrigemActionPerformed

    private void txtTamanhoMensagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTamanhoMensagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTamanhoMensagemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaParametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaParametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaParametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaParametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaParametros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JCheckBox chkACK;
    private javax.swing.JCheckBox chkFIN;
    private javax.swing.JCheckBox chkPSH;
    private javax.swing.JCheckBox chkRST;
    private javax.swing.JCheckBox chkSYN;
    private javax.swing.JCheckBox chkURG;
    private javax.swing.JLabel lblIpDestino;
    private javax.swing.JLabel lblIpOrigem;
    private javax.swing.JLabel lblJanelaRecepcao;
    private javax.swing.JLabel lblMegaBytes;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JLabel lblNumeroRecepcao;
    private javax.swing.JLabel lblNumeroSequencia;
    private javax.swing.JLabel lblPortaDestino;
    private javax.swing.JLabel lblPortaOrigem;
    private javax.swing.JLabel lblTamanhoMensagem;
    private javax.swing.JSlider sliderTamanhoMensagem;
    private javax.swing.JFormattedTextField txtIpDestino;
    private javax.swing.JFormattedTextField txtIpOrigem;
    private javax.swing.JFormattedTextField txtJanelaRecepcao;
    private javax.swing.JTextField txtMensagem;
    private javax.swing.JFormattedTextField txtNumeroRecepcao;
    private javax.swing.JTextField txtNumeroSequencia;
    private javax.swing.JFormattedTextField txtPortaDestino;
    private javax.swing.JFormattedTextField txtPortaOrigem;
    private javax.swing.JTextField txtTamanhoMensagem;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
